name: ðŸš€ Deploy manually to doubledeals/intasend & infinityfree 

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # Deploy to delta.doubledeals.co.ke
  deploy-to-delta:
    name: ðŸŽ‰ Deploy to intasend DoubleDeals
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files to intasend DoubleDeals
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.doubledeals.co.ke
          username: intasend@intasend.doubledeals.co.ke
          password: yKu!XjenMM6V
          server-dir: /  # The directory on the server to deploy files to

  # Deploy to InfinityFree

  deploy-to-infinityfree:
    name: ðŸŽ‰ Deploy to InfinityFree/intasend
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_37114096
          password: QcIDYuIrKJ # Store sensitive data in GitHub Secrets
          server-dir: /intasend.wuaze.com/htdocs/
          retries: 3                 # Retry the connection up to 3 times in case of timeout
          retryDelay: 10             # Wait 10 seconds before retrying after a failure
